name: "Archive ended YouTube live-stream → Telegram"

on:
  schedule:
    # 6 AM – 12 PM IST  (UTC+5:30)  →  00,30 0-6 UTC
    - cron: "0,30 0-6 * * *"
  workflow_dispatch:   # manual button

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: { python-version: "3.11" }

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install cookie plugin + export cookies
        env:
          EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          PASS:  ${{ secrets.GOOGLE_PASSWORD }}
        run: |
          pip install yt-dlp[default]  # brings in 'curl_cffi' cookie helper
          # one-shot login + cookie jar
          yt-dlp --username "$EMAIL" --password "$PASS" \
                 --cookies cookies.txt \
                 --no-download \
                 https://www.youtube.com
          # if you have 2-Step-Verification, append:
          # --twofactor <code>
          echo "✅ cookies.txt ready"

      - name: Install Python deps
        run: pip install python-telegram-bot google-api-python-client packaging

      - name: Download & Upload
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python archive.py